import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomePage from "./homePage";
import Navbar from "../components/Navbar";
import Works from "./works";
import Clients from "./clients";
import Footer from "../components/Footer";
import Header from './Header.js'
import FullServices from "./fullServices";
import About from './about'
import Doing from './doing'
import AboutUs from './aboutUs'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Santa Fé Gráfica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/art.png" />
      </Head>
      <Navbar />
			<HomePage />
      <FullServices/>
			<Works />
      <Header />
      <AboutUs />
			<Clients />
      <Doing />
      <About />
			<Footer />


    </div>
  )
}

export default Home
